/* Download the exact Latin woff2 files from Google Fonts and generate a local
   @font-face stylesheet, so fonts are self-hosted (no external request), can be
   preloaded, and never cause a layout shift. Run once:  node scripts/fetch-fonts.mjs */
import { mkdirSync, writeFileSync, createWriteStream } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import https from "node:https";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const FONT_DIR = resolve(ROOT, "public/fonts");
mkdirSync(FONT_DIR, { recursive: true });

// Modern UA so Google serves woff2.
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36";

const families = [
  { css: "Fraunces:opsz,wght@9..144,300;9..144,400", file: "fraunces", weights: { 300: "fraunces-300", 400: "fraunces-400" } },
  { css: "Manrope:wght@200;300;400;500", file: "manrope", weights: { 200: "manrope-200", 300: "manrope-300", 400: "manrope-400", 500: "manrope-500" } },
];

function get(url, opts = {}) {
  return new Promise((res, rej) => {
    https.get(url, { headers: { "User-Agent": UA }, ...opts }, (r) => {
      if (r.statusCode >= 300 && r.statusCode < 400 && r.headers.location) return res(get(r.headers.location, opts));
      const chunks = [];
      r.on("data", (c) => chunks.push(c));
      r.on("end", () => res(Buffer.concat(chunks)));
    }).on("error", rej);
  });
}

let cssOut = "/* Self-hosted fonts (Latin subset) — generated by scripts/fetch-fonts.mjs */\n";

for (const fam of families) {
  const url = `https://fonts.googleapis.com/css2?family=${fam.css}&display=swap`;
  const css = (await get(url)).toString("utf8");

  // Split into @font-face blocks; keep only the latin ones (unicode-range U+0000..).
  const blocks = css.split("@font-face").slice(1);
  for (const b of blocks) {
    const isLatin = /\/\* latin \*\//.test(css.slice(css.indexOf(b) - 20, css.indexOf(b))) || b.includes("U+0000-00FF");
    if (!b.includes("U+0000-00FF")) continue; // latin block has this range
    const weight = (b.match(/font-weight:\s*(\d+)/) || [])[1];
    const src = (b.match(/url\((https:[^)]+\.woff2)\)/) || [])[1];
    if (!weight || !src || !fam.weights[weight]) continue;

    const name = fam.weights[weight];
    const buf = await get(src);
    writeFileSync(resolve(FONT_DIR, `${name}.woff2`), buf);
    const fontFamily = fam.file === "fraunces" ? "Fraunces" : "Manrope";
    cssOut += `@font-face{font-family:'${fontFamily}';font-style:normal;font-weight:${weight};font-display:swap;src:url('/fonts/${name}.woff2') format('woff2');unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD;}\n`;
    console.log(`✓ ${name}.woff2  (${Math.round(buf.length / 1024)} KB)`);
  }
}

writeFileSync(resolve(ROOT, "src/fonts.css"), cssOut);
console.log("✓ wrote src/fonts.css");
